### ISSUE TITLE
SQL Connection error

### ISSUE THREAD

**Issue by UTexas80** [Bajdzis/vscode-database#63]
When I attempt to connect to SQL server the following error message is generated:
"Connection error! connect ENOENT localhost - connect ECONNREFUSED 127.0.0.1:3306"
I entered my valid username & password but was still refused access.

**Comment by RomanGotsiy** [comment]
I have a similar issue.

Happens only on a new version `2.0.0`. When I downgraded to `1.5.3` everything works as expected.

From Postgres server logs it looks like extension doesn't respect username and uses OS provided username.

**Comment by Bajdzis** [comment]
@UTexas80  @RomanGotsiy Please tell to which database server to connect. MySQL or Postgres ?

**Comment by RomanGotsiy** [comment]
Postgres in my case.

**Comment by RomanGotsiy** [comment]
@Bajdzis some more info. Hope that helps.

Just after upgrading to 2.0.0 I get the following error on VS Code start:

> PostgreSQL Error: error: role "romanhotsiy" does not exist at Connection.parseE (/Users/romanhotsiy/.vscode/extensions/bajdzis.vscode-database-2.0.0/node_modules/pg/lib/connection.js:567:11) at Connection.parseMessage (/Users/romanhotsiy/.vscode/extensions/bajdzis.vscode-database-2.0.0/node_modules/pg/lib/connection.js:391:17) at Socket.<anonymous> (/Users/romanhotsiy/.vscode/extensions/bajdzis.vscode-database-2.0.0/node_modules/pg/lib/connection.js:129:22) at Socket.emit (events.js:182:13) at addChunk (_stream_readable.js:279:12) at readableAddChunk (_stream_readable.js:264:11) at Socket.Readable.push (_stream_readable.js:219:10) at TCP.onread (net.js:636:20)

If I rename `user` to `username` (I was looking on changes between 1.5.3 and 2.0.0 and noticed you renamed it but in my saved config it remained as `user`) in vs code settings `database.connections` the message disappears.

Althogh, I can't connect to a database. I select one from the dropdown (which gets populated!) but nothing changes.

In dev tools I see the following error:

> ERR Cannot read property 'query' of null: TypeError: Cannot read property 'query' of null
    at queryPromise.Promise (/Users/romanhotsiy/.vscode/extensions/bajdzis.vscode-database-2.0.0/extension/engine/postgresql.js:149:29)
    at new Promise (<anonymous>)
    at PostgreSQLType.queryPromise (/Users/romanhotsiy/.vscode/extensions/bajdzis.vscode-database-2.0.0/extension/engine/postgresql.js:148:16)
    at getDatabase.Promise (/Users/romanhotsiy/.vscode/extensions/bajdzis.vscode-database-2.0.0/extension/engine/postgresql.js:179:22)
    at new Promise (<anonymous>)
    at PostgreSQLType.getDatabase (/Users/romanhotsiy/.vscode/extensions/bajdzis.vscode-database-2.0.0/extension/engine/postgresql.js:177:16)
    at Manager.getDatabase (/Users/romanhotsiy/.vscode/extensions/bajdzis.vscode-database-2.0.0/extension/Manager.js:126:35)
    at connectPostgreSQL.execution (/Users/romanhotsiy/.vscode/extensions/bajdzis.vscode-database-2.0.0/extension/action/extension.changeDB.js:9:25)
    at e._executeContributedCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:485:959)
    at e.$executeContributedCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:486:443)

**Comment by Bajdzis** [comment]
@RomanGotsiy Thanks for reply. I think the bug is fixed in 2.0.1 version. Could you check if that helped?

**Comment by UTexas80** [comment]
MySQL

**Comment by RomanGotsiy** [comment]
@Bajdzis, So the first issue is fixed. I no longer see the error message.

But the second issue is still here. I can't connect to the database. I see "Database not selected":

![db-vscode](https://user-images.githubusercontent.com/3975738/53838615-32224480-3f9e-11e9-8473-f66d7d121377.gif)

Also in VS Code dev tools, I see the following error message:
![image](https://user-images.githubusercontent.com/3975738/53838653-449c7e00-3f9e-11e9-8317-4dfe70a5ad31.png)

Looks like `this.connection` is null here:

https://github.com/Bajdzis/vscode-database/blob/d653a2f33a845669a570a8edb89d99842f26bb08/extension/engine/postgresql.js#L149

I can try to dig in deeper but I'll have to set up dev env for this. Let me know if you don't have time and want me to try.

---
I think this is a separate issue so you may want to close this and open a new one.

**Comment by UTexas80** [comment]
Still persists. I get the error message "Connection error! connect ECONNREFUSED 127.0.0.1:3306" when I attempt to login to MySQL
